package com.revature.service;

public class UserNotFoundException extends Exception {


        public void printError () {
            System.out.println("In exception");
        
        }

   
}
